Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2020-11, with the labels that each got.

#315 (Co)limits of general free diagrams of C-sets
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/wiring_diagrams/Algorithms.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/FreeDiagrams.jl
Labels: enhancement

#316 The UWD algebra of structured multicospans
  src/categorical_algebra/StructuredCospans.jl
  src/wiring_diagrams/Algebras.jl
  src/wiring_diagrams/WiringDiagrams.jl
  test/categorical_algebra/StructuredCospans.jl
  test/wiring_diagrams/Algebras.jl
  test/wiring_diagrams/WiringDiagrams.jl
Labels: enhancement

#320 Upgrade PrettyTables.jl to v0.10
  Project.toml
  src/categorical_algebra/CSetDataStructures.jl
Labels: cleanup

#321 Fix braidings in symmetric monoidal double categories
  src/theories/DoubleCategory.jl
  test/theories/DoubleCategory.jl
Labels: bug, cleanup

#322 Bundle legs of structured multicospans
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/StructuredCospans.jl
  test/categorical_algebra/FreeDiagrams.jl
  test/categorical_algebra/StructuredCospans.jl
Labels: enhancement

#325 Remove dependency on LightGraphs
  Project.toml
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/GraphCategories.jl
  src/categorical_algebra/Limits.jl
  src/graphs/BasicGraphs.jl
  src/graphs/GraphAlgorithms.jl
  src/graphs/Graphs.jl
  src/wiring_diagrams/Algorithms.jl
  src/wiring_diagrams/Expressions.jl
  src/wiring_diagrams/MonoidalDirected.jl
  test/graphs/BasicGraphs.jl
  test/graphs/GraphAlgorithms.jl
  test/graphs/Graphs.jl
  test/wiring_diagrams/Expressions.jl
Labels: cleanup, enhancement

#329 API docs for Graphs module
  docs/make.jl
  docs/src/apis/graphs.md
  src/graphs/BasicGraphs.jl
  src/graphs/PropertyGraphs.jl
Labels: docs

#334 Benchmarks for C-set graphs
  .github/workflows/benchmarks.yml
  .gitignore
  Project.toml
  benchmark/Graphs.jl
  benchmark/Project.toml
  benchmark/benchmarks.jl
  src/graphs/BasicGraphs.jl
  test/Project.toml
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/StructuredCospans.jl
  test/graphs/BasicGraphs.jl
Labels: performance

#336 Optimize getters and setters for C-sets
  .github/workflows/benchmarks.yml
  benchmark/Graphs.jl
  src/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: performance

#317 Pullback functorial data migration for C-sets
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: enhancement

#333 Convenient Macro for Creating ACSets
  src/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: enhancement

#343 Extend `migrate!` to attributed C-sets that are not empty
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: enhancement
