Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2020-10, with the labels that each got.

#278 Double Category of Squares
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Squares.jl
  src/core/GAT.jl
  src/theories/Category.jl
  src/theories/Theories.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/FreeDiagrams.jl
  test/categorical_algebra/Squares.jl
  test/theories/Category.jl
Labels: enhancement

#287 Embedded graphs
  docs/src/apis/categorical_algebra.md
  src/Catlab.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/Permutations.jl
  src/graphs/BasicGraphs.jl
  src/graphs/EmbeddedGraphs.jl
  src/graphs/Graphs.jl
  src/wiring_diagrams/Expressions.jl
  test/categorical_algebra/Permutations.jl
  test/graphs/EmbeddedGraphs.jl
  test/graphs/Graphs.jl
Labels: enhancement

#290 Copy parts between C-sets with different schemas
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/StructuredCospans.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: enhancement

#291 Substitute UWDs with arbitrary data attributes on junctions
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/StructuredCospans.jl
  src/wiring_diagrams/Undirected.jl
Labels: enhancement

#292 Abbreviated presentation syntax for generators of same type
  src/core/Present.jl
  test/core/Present.jl
Labels: enhancement

#293 Remove parts from C-sets
  src/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: enhancement

#295 Remove vertices and edges from graphs
  src/graphs/BasicGraphs.jl
  test/graphs/BasicGraphs.jl
Labels: enhancement

#296 Added matomo analytics tracker
  docs/make.jl
  docs/src/assets/analytics.js
Labels: docs

#297 Use our multigraph type for underlying graph of directed wiring diagram
  Project.toml
  src/categorical_algebra/CSetDataStructures.jl
  src/graphs/BasicGraphs.jl
  src/wiring_diagrams/Algorithms.jl
  src/wiring_diagrams/Directed.jl
  src/wiring_diagrams/Expressions.jl
  src/wiring_diagrams/MonoidalDirected.jl
  test/graphics/GraphvizWiringDiagrams.jl
  test/wiring_diagrams/Directed.jl
Labels: cleanup

#298 Composite morphisms and attributes in C-set accessors
  src/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: enhancement

#302 Indexing notation for C-sets
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CSets.jl
  src/graphs/BasicGraphs.jl
  src/wiring_diagrams/Undirected.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: enhancement

#305 Roll back added C-set parts on error
  src/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSetDataStructures.jl
  test/graphs/BasicGraphs.jl
Labels: cleanup

#303 Monoidal Double Categories
  src/theories/Category.jl
  src/theories/DoubleCategory.jl
  src/theories/Monoidal.jl
  src/theories/Theories.jl
  test/theories/Category.jl
  test/theories/DoubleCategory.jl
  test/theories/Theories.jl
Labels: enhancement

#311 Upgrade Documenter to fix slow build times
  docs/Project.toml
Labels: docs

#309 Scheduled UWDs: data structures and evaluation
  src/programs/RelationalPrograms.jl
  src/wiring_diagrams/ScheduleUndirected.jl
  src/wiring_diagrams/Undirected.jl
  src/wiring_diagrams/WiringDiagrams.jl
  test/wiring_diagrams/ScheduleUndirected.jl
  test/wiring_diagrams/WiringDiagrams.jl
Labels: enhancement

#313 Return views from C-set accessors where appropriate
  src/categorical_algebra/CSetDataStructures.jl
  src/wiring_diagrams/MonoidalUndirected.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: cleanup
