Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2020-07, with the labels that each got.

#183 Implementation of Decorated Cospans
  src/categorical_algebra/ShapeDiagrams.jl
Labels: enhancement

#187 C-sets as a generic data structure
  Manifest.toml
  Project.toml
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/Graphs.jl
  src/core/Syntax.jl
  src/graphics/Graphviz.jl
  src/graphics/GraphvizWiringDiagrams.jl
  src/graphics/YFilesWiringDiagrams.jl
  src/wiring_diagrams/GraphML.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/Graphs.jl
  test/graphics/Graphviz.jl
  test/graphics/GraphvizWiringDiagrams.jl
Labels: enhancement

#182 ENH: n-ary (co)products
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/ShapeDiagrams.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/ShapeDiagrams.jl
Labels: enhancement

#188 Remove Manifest.toml
  .gitignore
  Manifest.toml
  docs/Manifest.toml
Labels: cleanup

#189 Dependent Presentations
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/Graphs.jl
  src/core/Present.jl
  test/categorical_algebra/CSets.jl
  test/core/Present.jl
Labels: enhancement

#193 Remove spurious imports in ShapeDiagrams submodule
  src/categorical_algebra/ShapeDiagrams.jl
Labels: cleanup

#192 Undirected wiring diagrams
  docs/src/apis/wiring_diagrams.md
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Graphs.jl
  src/programs/ParseJuliaPrograms.jl
  src/wiring_diagrams/Algebraic.jl
  src/wiring_diagrams/Algorithms.jl
  src/wiring_diagrams/Directed.jl
  src/wiring_diagrams/Expressions.jl
  src/wiring_diagrams/GraphML.jl
  src/wiring_diagrams/JSON.jl
  src/wiring_diagrams/Serialization.jl
  src/wiring_diagrams/Undirected.jl
  src/wiring_diagrams/WiringDiagrams.jl
  test/categorical_algebra/CSets.jl
  test/graphics/GraphvizWiringDiagrams.jl
  test/wiring_diagrams/Algorithms.jl
  test/wiring_diagrams/Directed.jl
  test/wiring_diagrams/GraphML.jl
  test/wiring_diagrams/JSON.jl
  test/wiring_diagrams/Undirected.jl
  test/wiring_diagrams/WiringDiagrams.jl
Labels: enhancement

#197 Rename concrete types for FinOrd and FinOrdRel
  src/categorical_algebra/FinRelations.jl
  src/categorical_algebra/FinSets.jl
Labels: cleanup

#195 Unique and non-unique indexing of data in C-sets
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/Graphs.jl
  src/wiring_diagrams/Undirected.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/Graphs.jl
Labels: enhancement

#204 Bounds check before assigning C-set subpart
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/Graphs.jl
  test/categorical_algebra/CSets.jl
Labels: bug

#203 LinearMaps and LinearOperators are optional dependencies
  Project.toml
  src/linear_algebra/GLA.jl
  src/linear_algebra/LinearMapsExternal.jl
  src/linear_algebra/LinearOperatorsExternal.jl
  test/Project.toml
Labels: cleanup

#202 Macro to build undirected wiring diagrams via Julia-esque syntax
  Project.toml
  experiments/CompAlgebra/Project.toml
  experiments/CompAlgebra/src/AlgebraicNets.jl
  experiments/CompAlgebra/test/AlgebraicNets.jl
  src/categorical_algebra/CSets.jl
  src/programs/GenerateJuliaPrograms.jl
  src/programs/ParseJuliaPrograms.jl
  src/programs/ParseRelations.jl
  src/programs/Programs.jl
  src/wiring_diagrams/Undirected.jl
  test/categorical_algebra/CSets.jl
  test/programs/GenerateJuliaPrograms.jl
  test/programs/ParseRelations.jl
  test/programs/Programs.jl
Labels: enhancement

#206 Add link to emily riehls textbook to GAT description
  docs/src/index.md
Labels: docs

#207 Tensor notation for undirected wiring diagrams
  docs/src/apis/graphics.md
  docs/src/apis/programs.md
  docs/src/apis/wiring_diagrams.md
  src/programs/ParseRelations.jl
  src/programs/Programs.jl
  src/programs/RelationalPrograms.jl
  src/wiring_diagrams/Undirected.jl
  test/programs/ParseRelations.jl
  test/programs/Programs.jl
  test/programs/RelationalPrograms.jl
  test/wiring_diagrams/Undirected.jl
Labels: enhancement

#212 Drawing undirected wiring diagrams with Graphviz
  docs/literate/graphics/graphviz_wiring_diagrams.jl
  src/categorical_algebra/Graphs.jl
  src/graphics/Graphviz.jl
  src/graphics/GraphvizWiringDiagrams.jl
  test/categorical_algebra/Graphs.jl
  test/graphics/GraphvizWiringDiagrams.jl
Labels: enhancement, graphics

#214 Use MLStyle for pattern matching
  Project.toml
  src/core/GAT.jl
  src/core/Meta.jl
  src/core/Present.jl
  src/core/Syntax.jl
  src/graphics/GraphvizWiringDiagrams.jl
  src/graphics/TikZWiringDiagrams.jl
  src/programs/ParseJuliaPrograms.jl
  src/programs/RelationalPrograms.jl
Labels: cleanup

#208 improved `show` for CSets, and `vis` for graphical display
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/Graphs.jl
  src/graphics/Graphviz.jl
Labels: enhancement, graphics

#217 Use standard names for FinSet and FinRel
  src/categorical_algebra/FinRelations.jl
  src/categorical_algebra/FinSets.jl
  src/wiring_diagrams/Undirected.jl
  test/categorical_algebra/FinRelations.jl
  test/categorical_algebra/FinSets.jl
Labels: cleanup

#221 Undirected wiring diagrams as a hypergraph category
  docs/src/apis/wiring_diagrams.md
  src/categorical_algebra/CSets.jl
  src/theories/Monoidal.jl
  src/theories/MonoidalAdditive.jl
  src/theories/Relations.jl
  src/wiring_diagrams/Directed.jl
  src/wiring_diagrams/Expressions.jl
  src/wiring_diagrams/MonoidalDirected.jl
  src/wiring_diagrams/MonoidalUndirected.jl
  src/wiring_diagrams/Undirected.jl
  src/wiring_diagrams/WiringDiagrams.jl
  test/categorical_algebra/CSets.jl
  test/wiring_diagrams/Directed.jl
  test/wiring_diagrams/MonoidalDirected.jl
  test/wiring_diagrams/MonoidalUndirected.jl
  test/wiring_diagrams/Undirected.jl
  test/wiring_diagrams/WiringDiagrams.jl
Labels: enhancement
