Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2020-12, with the labels that each got.

#344 Port names in `@relation` macro
  src/programs/RelationalPrograms.jl
  test/programs/RelationalPrograms.jl
Labels: enhancement

#346 Consistent interface for UWD schedule evaluation
  src/linear_algebra/LinearAlgebra.jl
  src/linear_algebra/TensorNetworks.jl
  src/programs/RelationalPrograms.jl
  src/wiring_diagrams/Algebras.jl
  src/wiring_diagrams/ScheduleUndirected.jl
  test/linear_algebra/LinearAlgebra.jl
  test/linear_algebra/TensorNetworks.jl
  test/programs/RelationalPrograms.jl
  test/wiring_diagrams/ScheduleUndirected.jl
Labels: cleanup, enhancement

#337 Operad of Circular PortGraphs
  src/wiring_diagrams/CPortGraphs.jl
  src/wiring_diagrams/WiringDiagrams.jl
  test/wiring_diagrams/CPortGraphs.jl
  test/wiring_diagrams/WiringDiagrams.jl
Labels: enhancement

#347 Functions out of finite sets and other extensions
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/FinRelations.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/GraphCategories.jl
  src/categorical_algebra/PredicatedSets.jl
  src/categorical_algebra/Sets.jl
  src/categorical_algebra/StructuredCospans.jl
  src/wiring_diagrams/Undirected.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/PredicatedSets.jl
  test/categorical_algebra/Sets.jl
Labels: enhancement

#350 Support any Tables.jl-compliant backend for tables in C-set
  Project.toml
  src/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: enhancement

#348 Sort-merge algorithm for pullbacks
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  src/categorical_algebra/Sets.jl
  test/categorical_algebra/FinSets.jl
Labels: enhancement

#351 Bipartite graphs
  src/graphs/BasicGraphs.jl
  src/graphs/BipartiteGraphs.jl
  src/graphs/Graphs.jl
  test/graphs/BipartiteGraphs.jl
  test/graphs/Graphs.jl
Labels: enhancement

#355 Indexed `FinFunction`s and hash joins
  benchmark/FinSets.jl
  benchmark/Graphs.jl
  benchmark/README.md
  benchmark/benchmarks.jl
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/FinSets.jl
Labels: enhancement

#359 Multiway hash joins
  benchmark/FinSets.jl
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/FinSets.jl
Labels: enhancement, performance

#358 Conjunctive queries of ACSets and the UWD algebra of multispans
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Sets.jl
  src/graphs/BipartiteGraphs.jl
  src/wiring_diagrams/Algebras.jl
  test/Project.toml
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/FreeDiagrams.jl
  test/categorical_algebra/Sets.jl
  test/graphs/BipartiteGraphs.jl
  test/wiring_diagrams/Algebras.jl
Labels: enhancement

#361 Allow context to be left implicit in `@relation` macro
  src/programs/RelationalPrograms.jl
  test/programs/RelationalPrograms.jl
Labels: enhancement

#345 Querying ACSets
  src/categorical_algebra/ACSetViews.jl
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/ACSetViews.jl
  test/categorical_algebra/CategoricalAlgebra.jl
Labels: enhancement

#362 Expose function `pretty_tables` for ACSets
  src/categorical_algebra/CSetDataStructures.jl
Labels: enhancement

#364 Support for constants in conjunctive queries on ACSets
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Sets.jl
  src/wiring_diagrams/Algebras.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/Sets.jl
  test/wiring_diagrams/Algebras.jl
Labels: enhancement
