Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2020-06, with the labels that each got.

#166 Rename Doctrines module to Theories
  .github/workflows/experiments.yml
  docs/literate/graphics/composejl_wiring_diagrams.jl
  docs/literate/graphics/graphviz_wiring_diagrams.jl
  docs/literate/graphics/layouts_vs_drawings.jl
  docs/literate/graphics/tikz_wiring_diagrams.jl
  docs/literate/wiring_diagrams/diagrams_and_expressions.jl
  docs/literate/wiring_diagrams/wiring_diagram_basics.jl
  docs/make.jl
  docs/src/apis/core.md
  docs/src/apis/doctrines.md
  docs/src/apis/theories.md
  docs/src/index.md
  experiments/CompAlgebra/docs/algebraic_nets.jl
  experiments/CompAlgebra/src/AlgebraicNets.jl
  experiments/Markov/src/MarkovCategories.jl
  experiments/Markov/src/StochExpr.jl
  experiments/Markov/test/MarkovCategories.jl
  experiments/Markov/test/StochMapsExpr.jl
  src/Catlab.jl
  src/categorical_algebra/Permutations.jl
  src/core/Syntax.jl
  src/graphics/GraphvizWiringDiagrams.jl
  src/graphics/WiringDiagramLayouts.jl
  src/linear_algebra/GLA.jl
  src/linear_algebra/StructuredGLA.jl
  src/programs/GenerateJuliaPrograms.jl
  src/programs/ParseJuliaPrograms.jl
  src/theories/AdditiveMonoidal.jl
  src/theories/Category.jl
  src/theories/Monoidal.jl
  src/theories/Preorders.jl
  src/theories/Relations.jl
  src/theories/Theories.jl
  src/wiring_diagrams/Algebraic.jl
  src/wiring_diagrams/Expressions.jl
  src/wiring_diagrams/Layers.jl
  test/categorical_algebra/Permutations.jl
  test/core/GAT.jl
  test/core/Present.jl
  test/core/Syntax.jl
  test/graphics/ComposeWiringDiagrams.jl
  test/graphics/TikZWiringDiagrams.jl
  test/graphics/WiringDiagramLayouts.jl
  test/linear_algebra/GLA.jl
  test/linear_algebra/StructuredGLA.jl
  test/programs/GenerateJuliaPrograms.jl
  test/programs/ParseJuliaPrograms.jl
  test/runtests.jl
  test/theories/AdditiveMonoidal.jl
  test/theories/Category.jl
  test/theories/Monoidal.jl
  test/theories/Preorders.jl
  test/theories/Theories.jl
  test/wiring_diagrams/Algebraic.jl
  test/wiring_diagrams/Expressions.jl
Labels: cleanup

#167 Computing pushouts of spans in FinOrd
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/ShapeDiagrams.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/ShapeDiagrams.jl
Labels: enhancement

#168 Update links for new AlgebraicJulia organization
  README.md
  docs/make.jl
Labels: docs

#170 New logo for Catlab
  README.md
  docs/Manifest.toml
  docs/Project.toml
  docs/src/assets/favicon-16x16.png
  docs/src/assets/favicon-32x32.png
  docs/src/assets/favicon-base.png
  docs/src/assets/favicon.ico
  docs/src/assets/logo-500.png
  docs/src/assets/logo.png
  docs/src/assets/logo.svg
  docs/src/index.md
Labels: graphics

#169 Binary colimits in FinOrd
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/FinSets.jl
Labels: enhancement

#173 Binary limits in FinOrd
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/FinSets.jl
Labels: enhancement

#172 Link to Catlab channel on Julia Zulip
  README.md
Labels: docs

#174 Use macro in Base instead of Parameters.jl package
  Manifest.toml
  Project.toml
  src/graphics/ComposeWiringDiagrams.jl
  src/graphics/Graphviz.jl
  src/graphics/TikZWiringDiagrams.jl
  src/graphics/WiringDiagramLayouts.jl
Labels: cleanup

#175 Begin refactoring of GATs
  experiments/Markov/src/MarkovCategories.jl
  experiments/Markov/test/MarkovCategories.jl
  src/core/GAT.jl
  src/core/Rewrite.jl
  src/core/Syntax.jl
  src/programs/ParseJuliaPrograms.jl
  src/wiring_diagrams/Algebraic.jl
  src/wiring_diagrams/Expressions.jl
  test/core/GAT.jl
  test/core/Syntax.jl
  test/programs/ParseJuliaPrograms.jl
  test/wiring_diagrams/Algebraic.jl
Labels: cleanup

#176 Proper typing of presentations
  src/core/Present.jl
  src/programs/ParseJuliaPrograms.jl
  test/core/Present.jl
  test/programs/ParseJuliaPrograms.jl
Labels: cleanup

#177 GATs for categories with (co)limits
  src/categorical_algebra/FinSets.jl
  src/theories/AdditiveMonoidal.jl
  src/theories/Limits.jl
  src/theories/Monoidal.jl
  src/theories/Theories.jl
  test/theories/AdditiveMonoidal.jl
Labels: enhancement

#178 Categories of matrices
  Manifest.toml
  Project.toml
  docs/literate/graphics/composejl_wiring_diagrams.jl
  docs/literate/graphics/tikz_wiring_diagrams.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/FinRelations.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Matrices.jl
  src/graphics/WiringDiagramLayouts.jl
  src/linear_algebra/GLA.jl
  src/theories/AdditiveMonoidal.jl
  src/theories/Monoidal.jl
  src/theories/MonoidalAdditive.jl
  src/theories/MonoidalMultiple.jl
  src/theories/Relations.jl
  src/theories/Theories.jl
  src/wiring_diagrams/Algebraic.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/Matrices.jl
  test/linear_algebra/GLA.jl
  test/theories/Monoidal.jl
  test/theories/MonoidalAdditive.jl
  test/theories/Theories.jl
Labels: enhancement

#181 Remove the wiring layers submodule
  experiments/CompAlgebra/src/AlgebraicNets.jl
  experiments/CompAlgebra/src/MathFormulas.jl
  experiments/CompAlgebra/test/AlgebraicNets.jl
  experiments/CompAlgebra/test/MathFormulas.jl
  src/wiring_diagrams/Algebraic.jl
  src/wiring_diagrams/Algorithms.jl
  src/wiring_diagrams/Expressions.jl
  src/wiring_diagrams/Layers.jl
  src/wiring_diagrams/WiringDiagrams.jl
  test/wiring_diagrams/Layers.jl
  test/wiring_diagrams/WiringDiagrams.jl
Labels: cleanup

#180 The distributive bicategory of relations FinOrdRel
  src/categorical_algebra/FinRelations.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Matrices.jl
  src/theories/MonoidalMultiple.jl
  src/theories/Relations.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/FinRelations.jl
  test/categorical_algebra/FinSets.jl
Labels: enhancement
