Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2020-09, with the labels that each got.

#245 Another approach to empty StructArrays in C-sets
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/StructArrayWithLength.jl
Labels: cleanup

#249 Added code coverage github actions
  .github/workflows/codecov.yml
  README.md
Labels: docs

#251 Option to label boxes/junctions in Graphviz UWDs by number
  src/graphics/GraphvizWiringDiagrams.jl
  test/graphics/GraphvizWiringDiagrams.jl
Labels: graphics

#254 Restore original unit tests for C-sets
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: cleanup

#258 Improved type checking of add_parts
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: bug

#260 Half-edge graphs
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/Graphs.jl
  src/graphics/Graphics.jl
  src/graphics/Graphviz.jl
  src/graphics/GraphvizGraphs.jl
  src/graphics/GraphvizWiringDiagrams.jl
  test/categorical_algebra/Graphs.jl
  test/graphics/Graphics.jl
  test/graphics/Graphviz.jl
  test/graphics/GraphvizGraphs.jl
  test/graphics/GraphvizWiringDiagrams.jl
Labels: enhancement

#261 Documentation, bug fixes, and cleanup for attributed C-sets
  Project.toml
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Graphs.jl
  src/categorical_algebra/Limits.jl
  src/programs/RelationalPrograms.jl
  src/theories/Schema.jl
  src/wiring_diagrams/Undirected.jl
  test/categorical_algebra/CSets.jl
  test/theories/Schema.jl
Labels: bug, cleanup, docs

#267 Missing type parameters in abstract type for ACSets
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: bug

#268 Convert morphism expressions to UWDs
  src/programs/RelationalPrograms.jl
  src/theories/Monoidal.jl
  src/wiring_diagrams/Expressions.jl
  src/wiring_diagrams/MonoidalUndirected.jl
  src/wiring_diagrams/Undirected.jl
  test/programs/RelationalPrograms.jl
  test/wiring_diagrams/Expressions.jl
  test/wiring_diagrams/MonoidalUndirected.jl
Labels: enhancement

#269 Universal properties of limits and colimits in FinSet
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Limits.jl
  test/categorical_algebra/FinSets.jl
Labels: enhancement

#270 C-set morphisms
  src/categorical_algebra/CSetMorphisms.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/theories/Schema.jl
  test/categorical_algebra/CSetMorphisms.jl
  test/categorical_algebra/CategoricalAlgebra.jl
Labels: enhancement

#271 Limits of C-sets
  src/categorical_algebra/CSetMorphisms.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  test/categorical_algebra/CSetMorphisms.jl
  test/categorical_algebra/FreeDiagrams.jl
  test/categorical_algebra/Limits.jl
Labels: enhancement

#273 Colimits of C-sets
  src/categorical_algebra/CSetMorphisms.jl
  test/categorical_algebra/CSetMorphisms.jl
Labels: enhancement

#274 Colimits of attributed C-sets
  src/categorical_algebra/CSetMorphisms.jl
  test/categorical_algebra/CSetMorphisms.jl
Labels: enhancement

#275 General substitution of undirected wiring diagrams
  src/wiring_diagrams/Directed.jl
  src/wiring_diagrams/Undirected.jl
Labels: enhancement

#277 Don't restrict to `DataType` in C-set attributes
  src/categorical_algebra/CSets.jl
Labels: bug

#279 Structured cospans of attributed C-sets
  src/categorical_algebra/CSetMorphisms.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  src/categorical_algebra/StructuredCospans.jl
  src/theories/Schema.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/FreeDiagrams.jl
  test/categorical_algebra/Limits.jl
  test/categorical_algebra/StructuredCospans.jl
Labels: enhancement

#281 Structured cospans as a hypergraph category
  src/categorical_algebra/CSetMorphisms.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  src/categorical_algebra/StructuredCospans.jl
  test/categorical_algebra/CSetMorphisms.jl
  test/categorical_algebra/StructuredCospans.jl
Labels: enhancement

#282 Axioms for SMCs with diagonals
  src/theories/Monoidal.jl
  src/theories/MonoidalAdditive.jl
Labels: enhancement

#284 Pretty printing of C-set tables
  Project.toml
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: enhancement
