Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2021-07, with the labels that each got.

#446 DPO rewriting of C-sets
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/DPO.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/DPO.jl
Labels: enhancement

#451 Tighten types on ACSet constructor for data migration
  src/categorical_algebra/DataMigration.jl
Labels: bug

#453 Reference Semagrams in README
  README.md
  docs/src/index.md
Labels: docs

#458 FIX: resolve attribute error in Delta migration
  src/categorical_algebra/DataMigration.jl
  test/categorical_algebra/DataMigration.jl
Labels: bug

#460 Remove experimental parsing of DWDs from yFiles graphs
  src/graphics/Graphics.jl
  src/graphics/YFilesWiringDiagrams.jl
  test/graphics/Graphics.jl
  test/graphics/YFilesWiringDiagrams.jl
  test/graphics/data/yed_horizontal.graphml
  test/graphics/data/yed_vertical.graphml
Labels: cleanup

#461 Function to create subobject of C-set
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/DPO.jl
  test/categorical_algebra/CSets.jl
Labels: enhancement

#459 (Co)cartesian category instances from (co)products
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Limits.jl
  src/categorical_algebra/Sets.jl
  src/core/GAT.jl
  src/theories/Category.jl
  src/theories/HigherCategory.jl
  src/theories/Monoidal.jl
  src/theories/MonoidalAdditive.jl
  src/wiring_diagrams/Undirected.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/Sets.jl
  test/core/GAT.jl
Labels: enhancement

#464 Don't vectorize `incident` when attribute is a tuple
  src/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: bug

#457 ENH: add function for visualizing CPortGraphs
  src/graphics/GraphvizWiringDiagrams.jl
  test/graphics/GraphvizWiringDiagrams.jl
Labels: enhancement

#463 @acset macro fix for runtime values
  src/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: cleanup

#462 More acset documentation
  docs/src/apis/categorical_algebra.md
Labels: docs

#467 Algebra of sub-C-sets of a C-set
  docs/literate/graphs/subgraphs.jl
  docs/make.jl
  docs/src/apis/graphics.md
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/DPO.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Subobjects.jl
  src/graphics/GraphvizGraphs.jl
  src/graphics/GraphvizWiringDiagrams.jl
  src/theories/Preorders.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/FinSets.jl
  test/graphics/GraphvizGraphs.jl
  test/graphics/GraphvizWiringDiagrams.jl
Labels: enhancement

#466 Simplify implementation of @present macro
  src/core/Present.jl
Labels: cleanup

#468 Explain subobject meets and joins as adjoints
  docs/literate/graphs/subgraphs.jl
Labels: docs

#475 Restore support for non-vector iterators in `@acset` macro
  src/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: bug
