Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2021-11, with the labels that each got.

#543 Basic `show` methods for diagrams and diagram morphisms
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinCats.jl
  test/categorical_algebra/Diagrams.jl
Labels: enhancement

#544 Composite functions and functors
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/Categories.jl
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/FinCats.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Sets.jl
  src/theories/Schema.jl
  test/categorical_algebra/FinCats.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/Sets.jl
Labels: enhancement, cleanup

#545 Reduce general limits to limits of bipartite free diagrams
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/FinCats.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  test/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/FinCats.jl
  test/categorical_algebra/FreeDiagrams.jl
Labels: enhancement, performance

#548 Use meaningful column name when promoting trivial queries
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinCats.jl
  src/categorical_algebra/FinSets.jl
  src/graphs/BasicGraphs.jl
  src/programs/DiagrammaticPrograms.jl
  test/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/Diagrams.jl
  test/programs/DiagrammaticPrograms.jl
Labels: cleanup

#549 Deprecate data migration constructors for acsets
  src/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/DataMigrations.jl
Labels: cleanup, acsets

#552 Use meaningful element type in tabular sets
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/FinSets.jl
Labels: cleanup

#557 Better architecture for conjunctive data migration
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  test/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/FreeDiagrams.jl
Labels: enhancement, cleanup, acsets

#563 DOC: adding vignette for WDs as C-Sets
  docs/literate/wiring_diagrams/wd_cset.jl
  docs/make.jl
Labels: docs

#566 DOC: add sketch for SMCs
  docs/literate/sketches/meets.jl
  docs/literate/sketches/partitions.jl
  docs/literate/sketches/preorders.jl
  docs/literate/sketches/smc.jl
  docs/make.jl
Labels: docs

#567 Agglomerative data migration
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinCats.jl
  src/categorical_algebra/FinRelations.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Limits.jl
  src/programs/DiagrammaticPrograms.jl
  test/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/FinSets.jl
  test/programs/DiagrammaticPrograms.jl
Labels: enhancement, acsets

#571 DOC: Add content to SMC sketch
  docs/literate/sketches/smc.jl
Labels: docs

#570 Allow adding titles to wiring diagrams
  src/graphics/Graphviz.jl
  src/graphics/GraphvizWiringDiagrams.jl
  test/graphics/Graphviz.jl
Labels: enhancement, graphics

#569 Arbitrarily color boxes / junctions of a wiring diagram
  src/graphics/GraphvizWiringDiagrams.jl
Labels: enhancement, graphics

#575 Data migration using gluings of conjunctive queries
  docs/src/apis/programs.md
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/Categories.jl
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinCats.jl
  src/programs/DiagrammaticPrograms.jl
  src/theories/Schema.jl
  test/categorical_algebra/Categories.jl
  test/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/Diagrams.jl
  test/programs/DiagrammaticPrograms.jl
Labels: enhancement, acsets

#576 Data migration with data attributes
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinCats.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  src/categorical_algebra/Sets.jl
  src/graphs/BasicGraphs.jl
  src/programs/DiagrammaticPrograms.jl
  test/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/Limits.jl
  test/categorical_algebra/Sets.jl
Labels: enhancement, acsets

#579 DOC: Labelled Graph example with (co)limits
  docs/literate/graphs/graphs_label.jl
  docs/make.jl
Labels: docs

#580 GAT expressions and anonymous morphisms in `@diagram` macro
  src/core/Present.jl
  src/programs/DiagrammaticPrograms.jl
  test/categorical_algebra/DataMigrations.jl
  test/programs/DiagrammaticPrograms.jl
Labels: enhancement

#584 Colimits of finite sets with named elements
  src/categorical_algebra/Categories.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  test/categorical_algebra/FinSets.jl
Labels: enhancement
