Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2021-05, with the labels that each got.

#420 Refactor benchmarks to separate Catlab/LightGraphs
  benchmark/Graphs.jl
Labels: cleanup, performance

#423 Typo in dagger axiom of hypergraph category
  src/theories/Monoidal.jl
Labels: bug

#418 Theory of symmetric monoidal copresheaves
  src/theories/Monoidal.jl
Labels: enhancement

#419 Extra axioms for theory of SMCs
  src/theories/Monoidal.jl
Labels: cleanup

#421 Benchmark counting triangles in a graph
  benchmark/Graphs.jl
  src/categorical_algebra/CSets.jl
  src/graphs/GraphGenerators.jl
  src/wiring_diagrams/Algebras.jl
  test/graphs/GraphGenerators.jl
  test/wiring_diagrams/Algebras.jl
Labels: performance

#424 Enforce unitality of composition in default syntax systems
  experiments/CompAlgebra/src/AlgebraicNets.jl
  experiments/Markov/src/MarkovCategories.jl
  src/theories/Category.jl
  src/theories/HigherCategory.jl
  src/theories/Monoidal.jl
  src/theories/MonoidalAdditive.jl
  src/theories/Preorders.jl
  src/theories/Relations.jl
  test/theories/Category.jl
Labels: cleanup, enhancement

#428 Fix special case of cartesian product in FinSet bipartite limits
  src/categorical_algebra/FinSets.jl
  test/wiring_diagrams/Algebras.jl
Labels: bug

#430 Associativity and unitality of composition in FreeSchema
  src/theories/Schema.jl
  test/theories/Schema.jl
Labels: enhancement
