Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2021-08, with the labels that each got.

#376 Custom Structs for ACSets
  benchmark/Graphs.jl
  docs/src/apis/categorical_algebra.md
  src/Catlab.jl
  src/categorical_algebra/ACSetInterface.jl
  src/categorical_algebra/ACSetViews.jl
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/DPO.jl
  src/categorical_algebra/DataMigration.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/GraphCategories.jl
  src/categorical_algebra/IndexUtils.jl
  src/categorical_algebra/Limits.jl
  src/categorical_algebra/StructuredCospans.jl
  src/graphics/GraphvizGraphs.jl
  src/graphs/BasicGraphs.jl
  src/graphs/BipartiteGraphs.jl
  src/graphs/GraphAlgorithms.jl
  src/graphs/GraphGenerators.jl
  src/graphs/PropertyGraphs.jl
  src/programs/RelationalPrograms.jl
  src/theories/Schema.jl
  src/wiring_diagrams/Algebras.jl
  src/wiring_diagrams/CPortGraphs.jl
  src/wiring_diagrams/Directed.jl
  src/wiring_diagrams/MonoidalUndirected.jl
  src/wiring_diagrams/ScheduleUndirected.jl
  src/wiring_diagrams/Undirected.jl
  test/categorical_algebra/ACSetViews.jl
  test/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/DPO.jl
  test/categorical_algebra/DataMigration.jl
  test/categorical_algebra/StructuredCospans.jl
  test/graphs/BasicGraphs.jl
  test/theories/Schema.jl
  test/wiring_diagrams/CPortGraphs.jl
  test/wiring_diagrams/ScheduleUndirected.jl
Labels: enhancement

#465 Generic interface for pushout complements
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/DPO.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  test/categorical_algebra/DPO.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/FreeDiagrams.jl
Labels: enhancement, cleanup

#476 DOC: add a vignette for preorders
  docs/literate/sketches/preorders.jl
  docs/make.jl
Labels: docs

#486 Refactor type hierarchy in graphs module
  benchmark/Graphs.jl
  src/graphs/BasicGraphs.jl
  src/graphs/BipartiteGraphs.jl
  src/graphs/PropertyGraphs.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/StructuredCospans.jl
Labels: cleanup

#488 Invalid multiline comment block in vignette
  docs/literate/sketches/preorders.jl
Labels: bug, docs

#487 Different internal representations of subobjects
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Subobjects.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/DPO.jl
  test/categorical_algebra/FinSets.jl
Labels: cleanup, performance
