Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2021-04, with the labels that each got.

#397 DOC: add some documentation from answering Breiner questions.
  docs/src/apis/categorical_algebra.md
  docs/src/index.md
  src/categorical_algebra/FreeDiagrams.jl
Labels: docs

#398 Find homomorphisms of C-sets using backtracking search
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: enhancement

#400 Command-line switch to disable Literate.jl docs
  docs/make.jl
Labels: docs

#401 Extend backtracking search to C-set monomorphisms and isomorphisms
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: enhancement

#405 Constructors for common families of graphs
  benchmark/Graphs.jl
  src/graphs/GraphGenerators.jl
  src/graphs/Graphs.jl
  test/categorical_algebra/ACSetViews.jl
  test/categorical_algebra/CSets.jl
  test/graphics/GraphvizGraphs.jl
  test/graphs/GraphGenerators.jl
  test/graphs/Graphs.jl
  test/wiring_diagrams/Algebras.jl
  test/wiring_diagrams/CPortGraphs.jl
Labels: enhancement

#406 Cleanup following dropping of support for Julia v1.0
  Project.toml
  src/categorical_algebra/ACSetViews.jl
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Limits.jl
  src/categorical_algebra/Permutations.jl
  src/categorical_algebra/StructuredCospans.jl
  src/core/GAT.jl
  src/core/Meta.jl
  src/core/Present.jl
  src/core/Rewrite.jl
  src/core/Syntax.jl
  src/graphics/ComposeWiringDiagrams.jl
  src/graphics/Graphviz.jl
  src/graphics/GraphvizGraphs.jl
  src/graphics/GraphvizWiringDiagrams.jl
  src/graphics/TikZ.jl
  src/graphics/TikZWiringDiagrams.jl
  src/graphics/WiringDiagramLayouts.jl
  src/graphics/YFilesWiringDiagrams.jl
  src/graphs/BasicGraphs.jl
  src/graphs/GraphAlgorithms.jl
  src/graphs/PropertyGraphs.jl
  src/linear_algebra/TensorNetworks.jl
  src/programs/GenerateJuliaPrograms.jl
  src/programs/ParseJuliaPrograms.jl
  src/programs/RelationalPrograms.jl
  src/wiring_diagrams/Algebras.jl
  src/wiring_diagrams/Directed.jl
  src/wiring_diagrams/Expressions.jl
  src/wiring_diagrams/GraphML.jl
  src/wiring_diagrams/MonoidalUndirected.jl
  src/wiring_diagrams/ScheduleUndirected.jl
  src/wiring_diagrams/Undirected.jl
  test/Project.toml
  test/core/Meta.jl
  test/graphics/TikZWiringDiagrams.jl
Labels: cleanup

#402 add theories of co/Presheaf
  src/theories/Category.jl
Labels: enhancement

#409 Consolidate GATs of higher categories in one file
  src/theories/Category.jl
  src/theories/HigherCategory.jl
  src/theories/Preorders.jl
  src/theories/Theories.jl
  test/theories/Category.jl
  test/theories/HigherCategory.jl
  test/theories/Preorders.jl
  test/theories/Theories.jl
Labels: cleanup

#410 Generalized algebraic theory for displayed categories
  src/theories/Category.jl
Labels: enhancement

#412 Fix generators with no names in `@present` macro
  src/core/Present.jl
Labels: bug

#413 Convenience functions for homomorphism and isomorphism testing
  src/categorical_algebra/CSets.jl
  src/wiring_diagrams/Directed.jl
  test/categorical_algebra/CSets.jl
  test/graphics/YFilesWiringDiagrams.jl
  test/wiring_diagrams/Algorithms.jl
  test/wiring_diagrams/MonoidalDirected.jl
Labels: enhancement

#415 Finer control over termination of morphism backtracking search
  src/categorical_algebra/CSets.jl
Labels: cleanup, enhancement

#416 Default syntax systems and pretty-printing for (co)presheaves
  src/core/Syntax.jl
  src/theories/Category.jl
  src/theories/HigherCategory.jl
  src/theories/Theories.jl
  test/theories/Category.jl
  test/theories/Monoidal.jl
  test/theories/MonoidalAdditive.jl
  test/theories/Theories.jl
Labels: enhancement

#417 Theory of additive categories
  src/linear_algebra/GLA.jl
  src/theories/MonoidalAdditive.jl
Labels: enhancement
