Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2022-07, with the labels that each got.

#636 Fix bugs in removing acset parts when indices are present
  src/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSetDataStructures.jl
Labels: bug, acsets

#637 Syntactic sugar for empty/singleton sets in `@migration` macro
  src/programs/DiagrammaticPrograms.jl
  test/programs/DiagrammaticPrograms.jl
Labels: enhancement, acsets

#638 Fix type ambiguities with empty diagrams in data migration
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinCats.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Limits.jl
  test/categorical_algebra/DataMigrations.jl
  test/programs/DiagrammaticPrograms.jl
Labels: bug, acsets

#639 GAT for indexed monoidal categories
  src/theories/Category.jl
  src/theories/IndexedCategory.jl
  src/theories/Monoidal.jl
  src/theories/Theories.jl
Labels: enhancement, GATs

#562 Remove LinearAlgebra module
  .github/workflows/experiments.yml
  Project.toml
  docs/make.jl
  experiments/TensorNetworks/Project.toml
  experiments/TensorNetworks/src/TensorNetworks.jl
  experiments/TensorNetworks/test/ScheduleUndirected.jl
  experiments/TensorNetworks/test/TensorNetworks.jl
  experiments/TensorNetworks/test/runtests.jl
  src/Catlab.jl
  src/linear_algebra/GLA.jl
  src/linear_algebra/LinearAlgebra.jl
  src/linear_algebra/LinearMapsExternal.jl
  src/linear_algebra/LinearOperatorsExternal.jl
  src/linear_algebra/StructuredGLA.jl
  test/Project.toml
  test/linear_algebra/GLA.jl
  test/linear_algebra/LinearAlgebra.jl
  test/linear_algebra/StructuredGLA.jl
  test/runtests.jl
  test/wiring_diagrams/WiringDiagrams.jl
Labels: cleanup

#635 Move DPO related content to AlgebraicRewriting
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/DPO.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Limits.jl
  src/categorical_algebra/Slices.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/Slices.jl
Labels: cleanup

#640 Rename and export acset schemas
  benchmark/Graphs.jl
  docs/literate/diagrams/diagrams.jl
  docs/literate/graphs/graphs.jl
  docs/literate/graphs/graphs_label.jl
  docs/literate/sketches/cat_elements.jl
  docs/literate/sketches/meets.jl
  docs/literate/sketches/smc.jl
  docs/literate/wiring_diagrams/wd_cset.jl
  docs/src/apis/categorical_algebra.md
  src/categorical_algebra/CatElements.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/graphs/BasicGraphs.jl
  src/graphs/BipartiteGraphs.jl
  src/graphs/PropertyGraphs.jl
  src/programs/DiagrammaticPrograms.jl
  src/programs/RelationalPrograms.jl
  src/wiring_diagrams/Algebras.jl
  src/wiring_diagrams/CPortGraphs.jl
  src/wiring_diagrams/Directed.jl
  src/wiring_diagrams/MonoidalUndirected.jl
  src/wiring_diagrams/ScheduleUndirected.jl
  src/wiring_diagrams/Undirected.jl
  test/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/Diagrams.jl
  test/categorical_algebra/FinCats.jl
  test/categorical_algebra/StructuredCospans.jl
  test/core/Present.jl
  test/graphics/GraphvizCategories.jl
  test/programs/DiagrammaticPrograms.jl
Labels: cleanup, acsets

#641 Replace AutoHashEquals with StructEquality
  Project.toml
  experiments/CompAlgebra/Project.toml
  experiments/CompAlgebra/src/MathFormulas.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/Categories.jl
  src/categorical_algebra/CommutativeDiagrams.jl
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinCats.jl
  src/categorical_algebra/FinRelations.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  src/categorical_algebra/Sets.jl
  src/categorical_algebra/Slices.jl
  src/categorical_algebra/StructuredCospans.jl
  src/categorical_algebra/Subobjects.jl
  src/core/GAT.jl
  src/core/Meta.jl
  src/graphics/Graphviz.jl
  src/graphics/TikZ.jl
  src/wiring_diagrams/Directed.jl
  src/wiring_diagrams/MonoidalDirected.jl
  src/wiring_diagrams/MonoidalUndirected.jl
Labels: cleanup

#646 LooseAcsetTransformation type component coercion
  src/categorical_algebra/CSets.jl
Labels: bug, acsets

#645 Refactor and extend GATs for double categories
  src/categorical_algebra/CommutativeDiagrams.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/graphs/BasicGraphs.jl
  src/theories/Category.jl
  src/theories/HigherCategory.jl
  src/theories/Monoidal.jl
  src/theories/Theories.jl
  test/categorical_algebra/CommutativeDiagrams.jl
  test/theories/HigherCategory.jl
Labels: enhancement, cleanup, GATs

#620 Structured cospans of acsets with multiple objects in interface
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/StructuredCospans.jl
  test/categorical_algebra/StructuredCospans.jl
Labels: enhancement, acsets
