Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2022-12, with the labels that each got.

#718 Missing case in query promotion for `@migration` macro
  src/categorical_algebra/DataMigrations.jl
  src/programs/DiagrammaticPrograms.jl
  test/programs/DiagrammaticPrograms.jl
Labels: bug, acsets

#724 Missing `op` method for `Diagram{Any}`
  src/categorical_algebra/Diagrams.jl
  test/categorical_algebra/Diagrams.jl
Labels: bug

#715 Greatly simplify columns underlying acsets
  benchmark/Graphs.jl
  src/acsets/ACSetInterface.jl
  src/acsets/ACSets.jl
  src/acsets/ColumnImplementations.jl
  src/acsets/Columns.jl
  src/acsets/Defaults.jl
  src/acsets/DenseACSets.jl
  src/acsets/Mappings.jl
  src/acsets/PreimageCaches.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  test/acsets/ACSets.jl
  test/acsets/CSetDataStructures.jl
  test/acsets/Columns.jl
  test/acsets/Mappings.jl
Labels: cleanup, acsets

#723 Get Catlab version without assuming it is a dependency
  src/categorical_algebra/CSets.jl
Labels: bug
