Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2022-10, with the labels that each got.

#677 Hash method for ACSets
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/Diagrams.jl
  test/categorical_algebra/Limits.jl
Labels: bug, acsets

#681 Partiality in ACSets handled in a well-defined and well-understood way
  docs/src/index.md
  src/Catlab.jl
  src/acsets/ACSetInterface.jl
  src/acsets/ACSets.jl
  src/acsets/CSetDataStructures.jl
  src/acsets/ColumnImplementations.jl
  src/acsets/Columns.jl
  src/acsets/DenseACSets.jl
  src/acsets/IndexUtils.jl
  src/acsets/LVectors.jl
  src/acsets/Schemas.jl
  src/categorical_algebra/ACSetColumns.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/CatElements.jl
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  src/categorical_algebra/StructuredCospans.jl
  src/graphs/BasicGraphs.jl
  src/theories/Schema.jl
  src/theories/Theories.jl
  src/wiring_diagrams/Algebras.jl
  src/wiring_diagrams/Directed.jl
  test/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/Columns.jl
Labels: enhancement, cleanup, acsets

#688 Colimits of acsets with given type components
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: enhancement, acsets

#689 Fix unused type parameters related to acset schemas
  src/acsets/DenseACSets.jl
  src/categorical_algebra/DataMigrations.jl
Labels: cleanup, acsets

#691 Make conversion to Presentation from Schema preserve ordering
  src/acsets/CSetDataStructures.jl
Labels: bug, acsets

#693 Use intermediating AST in diagram macros
  src/programs/DiagrammaticPrograms.jl
  test/programs/DiagrammaticPrograms.jl
Labels: cleanup

#694 Literal values in `@free_diagram` and `@migration` macros
  docs/literate/categorical_algebra/diagrams.jl
  src/categorical_algebra/Diagrams.jl
  src/graphics/GraphvizCategories.jl
  src/programs/DiagrammaticPrograms.jl
  test/categorical_algebra/Diagrams.jl
  test/programs/DiagrammaticPrograms.jl
Labels: enhancement

#696 Parse diagram DSLs to ASTs at macro expansion time where possible
  src/programs/DiagrammaticPrograms.jl
Labels: cleanup

#697 Error message references undefined variable
  src/programs/DiagrammaticPrograms.jl
Labels: bug

#699 Typo in type declaration of `FinDomFunctionDict`
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/FinSets.jl
Labels: bug
