Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2022-01, with the labels that each got.

#590 DOC: add ACSetInterface to docs
  docs/src/apis/categorical_algebra.md
Labels: docs

#572 Expose DPO morphism relating input and output of rewriting
  src/categorical_algebra/DPO.jl
Labels: enhancement, acsets

#594 Docstrings not attached to acset types
  src/categorical_algebra/CSetDataStructures.jl
Labels: bug, acsets
