Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2022-03, with the labels that each got.

#607 Upgrade Convex.jl to v0.15
  docs/Project.toml
  src/graphics/ConvexExternal.jl
Labels: docs

#573 Initiality test for FinFunctors
  src/categorical_algebra/FinCats.jl
  src/graphs/GraphAlgorithms.jl
  src/graphs/PropertyGraphs.jl
  test/categorical_algebra/FinCats.jl
  test/graphs/GraphAlgorithms.jl
Labels: enhancement

#604 Category of elements action on morphisms and inverse constructions
  src/categorical_algebra/CatElements.jl
  test/categorical_algebra/CatElements.jl
Labels: enhancement

#610 add hash method for diagram/diagram hom
  src/categorical_algebra/Diagrams.jl
  test/categorical_algebra/Diagrams.jl
Labels: bug

#588 Benchmarks for paper
  benchmark/Graphs.jl
  benchmark/make_plots.jl
  benchmark/plots.jl
  src/categorical_algebra/ACSetInterface.jl
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/GraphCategories.jl
  src/graphs/BasicGraphs.jl
  src/graphs/GraphAlgorithms.jl
  src/graphs/GraphGenerators.jl
  src/graphs/Graphs.jl
  src/graphs/Searching.jl
  test/graphs/BasicGraphs.jl
  test/graphs/GraphGenerators.jl
  test/graphs/Searching.jl
Labels: performance, acsets
