Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2022-09, with the labels that each got.

#671 Bug fix for `permute` function
  src/wiring_diagrams/MonoidalDirected.jl
  test/wiring_diagrams/MonoidalDirected.jl
Labels: bug, wiring diagrams

#673 Type for graph underlying DWD has wrong supertype
  src/wiring_diagrams/Directed.jl
Labels: bug, wiring diagrams

#665 Refactor ACSets to use CompTime.jl
  Project.toml
  docs/src/apis/categorical_algebra.md
  src/Catlab.jl
  src/categorical_algebra/ACSetColumns.jl
  src/categorical_algebra/ACSetInterface.jl
  src/categorical_algebra/CSetDataStructures.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/FinSets.jl
  src/theories/Schema.jl
  src/wiring_diagrams/Directed.jl
  test/categorical_algebra/CSetDataStructures.jl
  test/categorical_algebra/CSets.jl
Labels: enhancement, acsets

#679 Small fix for Presentation -> SchemaDesc function
  src/theories/Schema.jl
Labels: bug, acsets

#663 Theory of groupoids, and syntax system for free groupoids
  src/core/Rewrite.jl
  src/theories/Category.jl
  test/theories/Category.jl
Labels: enhancement, GATs

#685 Rename monic/epic and allow tight acset transformations
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/Limits.jl
Labels: cleanup, acsets
