Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2022-08, with the labels that each got.

#649 Serialize and deserialize ACSet schemas to JSON
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/data/acset.schema.json
  test/Project.toml
  test/categorical_algebra/CSets.jl
Labels: enhancement, acsets

#657 Theory of double categories with tabulators
  src/categorical_algebra/Limits.jl
  src/theories/HigherCategory.jl
Labels: GATs

#664 Fix connected_component_bfs #634
  src/categorical_algebra/GraphCategories.jl
  test/graphs/GraphAlgorithms.jl
Labels: bug, graphs

#650 Compile with generators
  src/programs/GenerateJuliaPrograms.jl
  test/programs/GenerateJuliaPrograms.jl
Labels: enhancement

#669 Subsection of literate docs for categorical algebra
  docs/literate/categorical_algebra/acset_serialization.jl
  docs/literate/categorical_algebra/diagrams.jl
  docs/make.jl
Labels: docs
