Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2022-11, with the labels that each got.

#701 Option for acset `pretty_tables` to filter which tables to show
  src/acsets/ACSetInterface.jl
Labels: enhancement, acsets

#702 Minor documentation fix
  src/categorical_algebra/FinCats.jl
Labels: docs

#703 Clean up and tests for acset column system
  src/acsets/ColumnImplementations.jl
  src/acsets/Columns.jl
  src/acsets/DenseACSets.jl
  src/acsets/IndexUtils.jl
  src/acsets/LVectors.jl
  src/acsets/Schemas.jl
  test/acsets/ACSets.jl
  test/acsets/CSetDataStructures.jl
  test/acsets/Columns.jl
  test/acsets/IndexUtils.jl
  test/acsets/LVectors.jl
  test/acsets/Schemas.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/runtests.jl
Labels: cleanup, acsets

#704 Fix deprecations related to ordered dicts and varargs
  src/categorical_algebra/StructuredCospans.jl
  src/graphics/Graphviz.jl
  src/graphics/GraphvizGraphs.jl
Labels: cleanup

#705 Remove old and unused tests of acset columns
  test/categorical_algebra/Columns.jl
Labels: cleanup, acsets

#717 Option `product_attrs` for ACSet limits
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: enhancement, acsets
