Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2023-07, with the labels that each got.

#820 Benchmark two different implementations of making a path graph
  benchmark/Graphs.jl
Labels: performance, graphs

#821 Enumerating partial overlaps as an iterator
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: performance, acsets

#824 Make `neighbors` for graphs faster by returning an iterator
  src/graphs/BasicGraphs.jl
  src/graphs/GraphAlgorithms.jl
  src/graphs/Searching.jl
  test/graphs/BasicGraphs.jl
Labels: performance, graphs

#818 Category of elements for general C-sets
  src/categorical_algebra/CatElements.jl
  test/categorical_algebra/CatElements.jl
Labels: cleanup, acsets

#829 Better support for attributes in sigma migrations
  src/categorical_algebra/Chase.jl
  src/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/DataMigrations.jl
Labels: enhancement, acsets

#833 Forward compatibility for mark-as-deleted acsets
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: cleanup, acsets

#786 Subobject classifier + Internal hom for C-Sets
  Project.toml
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinSets.jl
  src/gats/Presentations.jl
  test/categorical_algebra/DataMigrations.jl
  test/gats/Presentations.jl
Labels: enhancement, acsets
