Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2023-06, with the labels that each got.

#796 Upgrade to ACSets.jl v0.2
  Project.toml
  benchmark/Graphs.jl
  experiments/TensorNetworks/src/TensorNetworks.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/categorical_algebra/Limits.jl
  src/programs/RelationalPrograms.jl
  src/wiring_diagrams/Algebras.jl
  src/wiring_diagrams/Expressions.jl
Labels: acsets

#798 Fix bug with uninitialized data in `oapply` for multispans
  src/wiring_diagrams/Algebras.jl
Labels: bug, wiring diagrams

#792 Breaking change to data migration API
  docs/literate/sketches/cat_elements.jl
  src/categorical_algebra/DataMigrations.jl
  src/programs/DiagrammaticPrograms.jl
  test/categorical_algebra/DataMigrations.jl
  test/programs/DiagrammaticPrograms.jl
Labels: cleanup, acsets

#799 Clean up API for functorality and naturality testing
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinCats.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/FinCats.jl
Labels: cleanup, acsets

#815 Fixed typos: colimts -> colimits
  docs/src/apis/categorical_algebra.md
Labels: docs

#816 Fix omitted case in `leftmost_arg`
  src/programs/DiagrammaticPrograms.jl
  test/programs/DiagrammaticPrograms.jl
Labels: bug

#808 Subobject with attribute variables
  Project.toml
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/CSets.jl
Labels: acsets

#817 More support for subacsets with variables
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/CSets.jl
Labels: acsets
