Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2023-12, with the labels that each got.

#868 Make sure you can add SetFunctionCallables to BipartiteDiagrams during limit computation
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/DataMigrations.jl
Labels: bug

#875 Upgrade to Documenter v1
  docs/Project.toml
  docs/make.jl
Labels: docs

#879 Port to JSON3.jl
  Project.toml
  docs/Project.toml
  docs/literate/graphics/graphviz_wiring_diagrams.jl
  src/graphics/GraphvizWiringDiagrams.jl
  src/wiring_diagrams/GraphML.jl
  src/wiring_diagrams/JSON.jl
  test/Project.toml
  test/graphics/GraphvizGraphs.jl
  test/graphics/GraphvizWiringDiagrams.jl
  test/wiring_diagrams/JSON.jl
Labels: cleanup

#880 Remove `experiments` folder
  .github/workflows/experiments.yml
  experiments/Markov/Project.toml
  experiments/Markov/src/Markov.jl
  experiments/Markov/src/MarkovCategories.jl
  experiments/Markov/src/StochExpr.jl
  experiments/Markov/test/MarkovCategories.jl
  experiments/Markov/test/StochMapsExpr.jl
  experiments/Markov/test/runtests.jl
  experiments/README.md
  experiments/TensorNetworks/Project.toml
  experiments/TensorNetworks/src/TensorNetworks.jl
  experiments/TensorNetworks/test/ScheduleUndirected.jl
  experiments/TensorNetworks/test/TensorNetworks.jl
  experiments/TensorNetworks/test/runtests.jl
  src/wiring_diagrams/ScheduleUndirected.jl
  src/wiring_diagrams/WiringDiagrams.jl
Labels: cleanup
