Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2023-09, with the labels that each got.

#843 Move acset homomorphism search into own submodule
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/CatElements.jl
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/Chase.jl
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/HomSearch.jl
  src/wiring_diagrams/Algebras.jl
  src/wiring_diagrams/Directed.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/HomSearch.jl
Labels: cleanup, acsets, infrastructure

#823 Data migrations with Julia functions on attributes
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/Chase.jl
  src/categorical_algebra/DataMigrations.jl
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinCats.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/FreeDiagrams.jl
  src/gats/Presentations.jl
  src/gats/Rewriting.jl
  src/gats/SyntaxSystems.jl
  src/graphics/GraphvizCategories.jl
  src/graphs/BasicGraphs.jl
  src/programs/DiagrammaticPrograms.jl
  src/theories/Category.jl
  src/theories/Schema.jl
  test/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/Diagrams.jl
  test/programs/DiagrammaticPrograms.jl
  test/runtests.jl
  test/theories/Category.jl
  test/theories/Schema.jl
Labels: enhancement, acsets

#846 Remove DataMigrations code from Catlab
  docs/literate/categorical_algebra/diagrams.jl
  docs/make.jl
  docs/src/apis/programs.md
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/Diagrams.jl
  src/categorical_algebra/FinCats.jl
  src/categorical_algebra/FunctorialDataMigrations.jl
  src/programs/DiagrammaticPrograms.jl
  src/programs/Programs.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/DataMigrations.jl
  test/categorical_algebra/FunctorialDataMigrations.jl
  test/programs/DiagrammaticPrograms.jl
  test/programs/Programs.jl
Labels: acsets

#710 Delta migration of acset transformations
  src/categorical_algebra/Chase.jl
  src/categorical_algebra/FunctorialDataMigrations.jl
  test/categorical_algebra/Chase.jl
  test/categorical_algebra/FunctorialDataMigrations.jl
Labels: enhancement, acsets, infrastructure

#854 Unbreak `makemap` from `attrMigr` branch
  src/categorical_algebra/FinCats.jl
Labels: bug

#855 Consistent whitespace in runtests.jl
  test/runtests.jl
Labels: cleanup

#856 Export named graphs from `Catlab.Graphs`
  src/categorical_algebra/FinCats.jl
  src/categorical_algebra/FunctorialDataMigrations.jl
  src/graphs/BasicGraphs.jl
  src/graphs/GraphSearching.jl
  src/graphs/Graphs.jl
  src/graphs/NamedGraphs.jl
  test/graphs/GraphAlgorithms.jl
  test/graphs/GraphSearching.jl
  test/graphs/Graphs.jl
  test/graphs/NamedGraphs.jl
Labels: enhancement, graphs

#858 Use named graphs API in Graphviz visualization
  docs/src/apis/categorical_algebra.md
  docs/src/apis/graphs.md
  src/graphics/GraphvizCategories.jl
  src/graphics/GraphvizGraphs.jl
  src/graphs/NamedGraphs.jl
  test/graphics/GraphvizGraphs.jl
  test/graphs/NamedGraphs.jl
Labels: enhancement, graphics, graphs
