Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2024-05, with the labels that each got.

#900 Smoothing interaction between VarSets and actual sets and functions
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Sets.jl
  test/categorical_algebra/FinSets.jl
  test/categorical_algebra/Sets.jl
Labels: cleanup

#909 Fix Heyting subtraction for ACSets with variables
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
Labels: bug, acsets

#912 Upgrade to Convex v0.16
  Project.toml
  ext/CatlabConvexExt.jl
Labels: graphics
