Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2024-01, with the labels that each got.

#881 Adding missing `compose` and `id` methods for pointed set schemas
  src/categorical_algebra/FinCats.jl
Labels: bug

#882 Add missing SigmaMigrationFunctor constructors for DynamicACSets
  src/categorical_algebra/FunctorialDataMigrations.jl
  test/categorical_algebra/FunctorialDataMigrations.jl
Labels: bug

#873 Constrain acset hom search to specified subsets
  src/categorical_algebra/HomSearch.jl
  test/categorical_algebra/HomSearch.jl
Labels: enhancement, acsets

#883 Rename `Slices` to `SliceCategories` to avoid name conflict
  src/categorical_algebra/CategoricalAlgebra.jl
  src/categorical_algebra/SliceCategories.jl
  test/categorical_algebra/CategoricalAlgebra.jl
  test/categorical_algebra/SliceCategories.jl
Labels: cleanup
