Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2024-02, with the labels that each got.

#886 Overlap iterator output span order bugfix + ignoring of specific attrtypes
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/HomSearch.jl
  test/categorical_algebra/HomSearch.jl
Labels: bug, enhancement, acsets

#831 Support for mark-as-deleted in acsets
  src/categorical_algebra/ACSetsGATsInterop.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/HomSearch.jl
  test/categorical_algebra/CSets.jl
  test/categorical_algebra/HomSearch.jl
Labels: acsets, infrastructure

#887 Enumerate subobjects of acsets with attribute variables
  src/categorical_algebra/HomSearch.jl
  test/categorical_algebra/HomSearch.jl
Labels: bug, enhancement, acsets

#890 Fixed typo. "commute must" -> "must commute".
  src/categorical_algebra/CSets.jl
Labels: docs
