Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2024-06, with the labels that each got.

#914 Code simplification from equations in schema
  Project.toml
  src/categorical_algebra/ACSetsGATsInterop.jl
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FunctorialDataMigrations.jl
  test/categorical_algebra/ACSetsGATsInterop.jl
  test/categorical_algebra/FunctorialDataMigrations.jl
Labels: enhancement, cleanup, acsets

#915 Redesign ACSetFunctors when there are AttrVars
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/FinSets.jl
Labels: cleanup, acsets

#917 Fix constructor of acset from `FinDomFunctor` in varacset case
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/CSets.jl
Labels: bug, acsets

#919 Fix construction of varacset from `FinDomFunctor`
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  test/categorical_algebra/CSets.jl
Labels: bug, acsets

#918 Monic constraint and `no_bind` kwarg for AttrVars in hom search
  src/categorical_algebra/HomSearch.jl
  test/categorical_algebra/Chase.jl
  test/categorical_algebra/HomSearch.jl
Labels: bug, enhancement, acsets
