Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2024-04, with the labels that each got.

#898 Fix types in graph algorithms
  src/graphs/GraphAlgorithms.jl
  src/graphs/GraphSearching.jl
Labels: bug, graphs

#901 Missing ACSetsGATsInterop methods
  src/categorical_algebra/ACSetsGATsInterop.jl
Labels: bug, acsets

#899 Cartesian transformations between acsets
  src/categorical_algebra/CSets.jl
  src/categorical_algebra/FinSets.jl
  src/categorical_algebra/Limits.jl
  test/categorical_algebra/CSets.jl
Labels: enhancement, acsets

#902 Bump dependency on ACSets.jl
  Project.toml
Labels: acsets

#905 Fix typo in `product` keyword arguments
  src/categorical_algebra/CSets.jl
Labels: bug
