Repository AlgebraicJulia/Catlab.jl, pull requests merged in 2024-10, with the labels that each got.

#943 Fixes for Julia v1.11
  src/categorical_algebra/CSets.jl
  test/categorical_algebra/HomSearch.jl
Labels: bug, acsets

#941 Fix empty collection typing bug
  src/categorical_algebra/HomSearch.jl
Labels: bug, acsets

#947 Floating viewer for Graphviz output
  src/graphics/Graphviz.jl
Labels: enhancement, graphics

#852 Add Sheaf implementation
  docs/literate/sketches/sheaves.jl
  docs/make.jl
  docs/src/apis/sheaves.md
  src/Catlab.jl
  src/sheaves/FVect.jl
  src/sheaves/Sheaves.jl
  test/runtests.jl
  test/sheaves/sheaves.jl
Labels: enhancement
